### ISSUE TITLE
Error in ContextType

### ISSUE THREAD

**Issue by lfkdsk** [Xython/YAPyPy#60]
``` python
from yapypy.utils.easy_debug import *

async def f(i):
    return i
async def run_list():
    return [await c for c in [f(1), f(41)]]
assert run_async(run_list()) == ([], [1, 41])

```

**Comment by lfkdsk** [comment]
``` python
Connected to pydev debugger (build 182.4505.26)
Traceback (most recent call last):
  File "/Users/liufengkai/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/182.4505.26/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Users/liufengkai/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/182.4505.26/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/liufengkai/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/182.4505.26/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/liufengkai/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/182.4505.26/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/liufengkai/Documents/Code/personal-projects/YAPyPy/test_fuck.py", line 13, in <module>
    yapypy_test_code(code, True)
  File "/Users/liufengkai/Documents/Code/personal-projects/YAPyPy/yapypy/utils/easy_debug.py", line 48, in yapypy_test_code
    c = py_compile(res)
  File "/Users/liufengkai/Documents/Code/personal-projects/YAPyPy/yapypy/extended_python/py_compile.py", line 18, in py_compile
    raise exc
  File "/Users/liufengkai/Documents/Code/personal-projects/YAPyPy/yapypy/extended_python/py_compile.py", line 15, in py_compile
    py_emit(node.it, ctx)
  File "<string>", line 8, in new_func
  File "/Users/liufengkai/Documents/Code/personal-projects/YAPyPy/yapypy/extended_python/emit_impl/__init__.py", line 113, in py_emit
    py_emit(each, ctx)
  File "<string>", line 8, in new_func
  File "/Users/liufengkai/Documents/Code/personal-projects/YAPyPy/yapypy/extended_python/emit_impl/__init__.py", line 107, in py_emit
    py_emit(node.it, ctx)
  File "<string>", line 8, in new_func
  File "/Users/liufengkai/Documents/Code/personal-projects/YAPyPy/yapypy/extended_python/emit_impl/new_context.py", line 158, in py_emit
    emit_function(node, new_ctx, is_async=True)
  File "/Users/liufengkai/Documents/Code/personal-projects/YAPyPy/yapypy/extended_python/emit_impl/new_context.py", line 37, in emit_function
    py_emit(each, new_ctx)
  File "<string>", line 8, in new_func
  File "/Users/liufengkai/Documents/Code/personal-projects/YAPyPy/yapypy/extended_python/emit_impl/simple_stmt.py", line 15, in py_emit
    py_emit(node.value, ctx)
  File "<string>", line 8, in new_func
  File "/Users/liufengkai/Documents/Code/personal-projects/YAPyPy/yapypy/extended_python/emit_impl/__init__.py", line 107, in py_emit
    py_emit(node.it, ctx)
  File "<string>", line 8, in new_func
  File "/Users/liufengkai/Documents/Code/personal-projects/YAPyPy/yapypy/extended_python/emit_impl/comprehensions.py", line 380, in py_emit
    is_async_outside, first_iter = _emit_comprehension(ctx, node.generators, delay)
  File "/Users/liufengkai/Documents/Code/personal-projects/YAPyPy/yapypy/extended_python/emit_impl/comprehensions.py", line 170, in _emit_comprehension
    action()
  File "/Users/liufengkai/Documents/Code/personal-projects/YAPyPy/yapypy/extended_python/emit_impl/comprehensions.py", line 377, in delay
    py_emit(node.elt, ctx)
  File "<string>", line 8, in new_func
  File "/Users/liufengkai/Documents/Code/personal-projects/YAPyPy/yapypy/extended_python/emit_impl/constrains.py", line 51, in py_emit
    raise exc
  File "<unknown>", line 7
SyntaxError: await outside async functions.
```

**Comment by thautwarm** [comment]
fixed.

**Comment by thautwarm** [comment]
use `snippet.py` to generate concrete bytecode information and bytecode instructions from 
```python
async def f():
    return [await a for a in b]

async def g():
    return [await a async for a in b]
```
